# vim:fileencoding=utf-8:foldmethod=marker

## Window
window_padding_width 2 2 0
background_opacity 0.95
macos_hide_titlebar yes
# active_border_color none

## Font Family
font_family      MonoLisa 	 
bold_font        MonoLisa Bold
italic_font      MonoLisa Book Italic
bold_italic_font MonoLisa Bold Italic

## Line and font size
font_size 16
adjust_line_height 16
adjust_column_width 0
adjust_baseline -2

## Ligatures
disable_ligatures cursor

## Border
active_border_color #33467C
inactive_border_color #293e42


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
